site_name: the Lever level editor
theme:
  name: "material"
  logo:
    icon: "videogame_asset"
  palette:
    primary: "red"
repo_name: "zsty/lever"
edit_uri: "edit/master/docs/docs"
repo_url: "https://github.com/zsty/lever"
